In [3]:
# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

# Exercises

### Exercise 1 - Load the data in a csv file into a dataframe

In [17]:
URL2 = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-BD0231EN-SkillsNetwork/datasets/seeds.csv"

Load the seeds dataset available at URL2

In [18]:
df2 = pd.read_csv(URL)

<details>
    <summary>Click here for a Hint</summary>
    
Use the read_csv function

</details>

<details>
    <summary>Click here for Solution</summary>

```python
df2 = pd.read_csv(URL2)
```

</details>

### Exercise 2 - Decide how many clusters to create

Cluster the data into 4 clusters

In [19]:
number_of_clusters = 4

<details>
    <summary>Click here for a Hint</summary>
    
set the variable number_of_clusters
</details>

<details>
    <summary>Click here for Solution</summary>

```python
number_of_clusters = 4
```

</details>

### Exercise 3 - Create a clustering model

Create a clustering model and train it using the data in the dataframe

In [20]:
cluster = KMeans(n_clusters = number_of_clusters)
result = cluster.fit_transform(df2)

<details>
    <summary>Click here for a Hint</summary>
    
use the fit_transform of KMeans
</details>

<details>
    <summary>Click here for Solution</summary>

```python
cluster = KMeans(n_clusters = number_of_clusters)
result = cluster.fit_transform(df2)
```

</details>

In [21]:
print(cluster.cluster_centers_)

[[ 9062.30714286  3063.66428571  3855.63214286  2795.01428571]
 [36144.48275862  5471.46551724  6128.79310345  6298.65517241]
 [ 4713.7826087  10877.75       17352.27173913  1531.        ]
 [21263.7        37443.3        46710.6         6287.2       ]]

### Exercise 4 - Make Predictions

Make the predictions and save them into the column "cluster_number"

In [22]:
df2['cluster_number'] = cluster.predict(df2)

<details>
    <summary>Click here for a Hint</summary>
    
use cluster.predict
</details>

<details>
    <summary>Click here for Solution</summary>

```python
df2['cluster_number'] = cluster.predict(df2)

```

</details>

In [23]:
df2.sample(5)

     Fresh_Food  Milk  Grocery  Frozen_Food  cluster_number
192        5509  1461     2251          547               0
90        11405   596     1638         3347               0
237       18692  3838      593         4634               0
357          37  1275    22272          137               2
276       27901  3749     6964         4479               1

Print the cluster numbers and the number of seeds in each cluster

In [24]:
df2.cluster_number.value_counts()

0    280
2     92
1     58
3     10
Name: cluster_number, dtype: int64

<details>
    <summary>Click here for a Hint</summary>
    
use the value_counts() method on cluster_number column
</details>

<details>
    <summary>Click here for Solution</summary>

```python
df2.cluster_number.value_counts()

```

</details>